@testset "Documentation contracts" begin
    binding = Base.Docs.Binding(Avro, Symbol("encode!"))
    @test haskey(Base.Docs.meta(Avro), binding)

    root = normpath(joinpath(@__DIR__, ".."))
    readme = read(joinpath(root, "README.md"), String)
    changelog = read(joinpath(root, "CHANGELOG.md"), String)
    encoding = read(joinpath(root, "docs", "src", "manual", "encoding.md"), String)
    container = read(joinpath(root, "docs", "src", "manual", "container.md"), String)
    security = read(joinpath(root, "docs", "src", "manual", "limits-and-security.md"), String)
    logical = read(joinpath(root, "docs", "src", "manual", "logicaltypes.md"), String)
    containersource = read(joinpath(root, "src", "container.jl"), String)
    flatreadme = lowercase(replace(readme, r"\s+" => " "))
    flatchangelog = lowercase(replace(changelog, r"\s+" => " "))
    flatcontainer = lowercase(replace(container, r"\s+" => " "))
    flatsecurity = lowercase(replace(security, r"\s+" => " "))

    @test occursin("`DatumReader` objects are safe to share across tasks", encoding)
    @test occursin("`DatumWriter` retains reusable encoder", encoding) && occursin("single-owner", encoding)
    @test occursin("`datumwriter` retains reusable mutable state and is single-owner", flatsecurity)
    @test occursin("`atomic=false`, the destination is opened in place", flatcontainer)
    @test occursin("failure can leave it truncated or containing complete blocks plus a partial final block", flatcontainer)
    @test occursin("does not sync the directory", flatcontainer)
    @test occursin("the first failure poisons the writer", flatcontainer)
    @test occursin("including a rejected datum or limit failure", flatcontainer)
    @test occursin("The first failure poisons the writer", containersource)
    @test occursin("WriterClosedError` carries the original cause", containersource)

    @test !occursin("every logical type", lowercase(readme))
    @test !occursin("complete implementation of the avro specification", lowercase(changelog))
    @test !occursin("every logical type", lowercase(logical))
    @test occursin("big-decimal", logical) && occursin("deferred", logical)
    @test occursin("Avro.Rows(\"old.avro\"; legacy=:avrojl1, decimal_byteorder=:little)", readme)
    @test occursin("reports header and framing issues", flatreadme)
    @test occursin("does not decode blocks or infer decimal byte order", flatreadme)
    @test !occursin("reports what a file needs", flatreadme)
    @test !occursin("1.x data defects are detectable", flatchangelog)
    @test occursin("does not diagnose payload padding or decimal byte order", flatchangelog)
    resolvingapis = "`reader_schema=` on `avro.decode`, `avro.datumreader`, `avro.decodesingle`, " *
                    "`avro.table`, and `avro.rows`"
    @test occursin(resolvingapis, flatreadme)
    @test occursin(resolvingapis, flatchangelog)
    @test !occursin("`reader_schema=` on every read path", flatreadme)
    @test !occursin("`reader_schema=` on every read path", flatchangelog)
end
