name = "Avro"
uuid = "65fc3dcb-49af-4f0c-a340-607eef534a14"
authors = ["Jacob Quinn <quinn.jacobd@gmail.com> and contributors"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1"

[targets]
test = ["Test"]
